services:
  app:
    image: ghcr.io/mrdurb/gambling-with-friends-in-tg:latest
    restart: unless-stopped
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      APP_LINK: ${APP_LINK}
    volumes:
      - ./data:/data

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data

volumes:
  caddy_data:
